### ISSUE TITLE
 ESBMC-AI

### ISSUE THREAD

**Issue by kaixin6321** [esbmc/esbmc-ai#110]
Hi yiannis,

Hi yiannis, I am a master student of Prof. Lucas and I chose to study his ESBMC-AI framework.  so I was wondering if I could ask you some questions on this topic.

After I successfully downloaded and deployed the latest version of ESBMC and the ESBMC-AI framework, I wasn't able to operate as you did in the youtube video. My output: none. i don't know why this is happening.

Warm regards,
kaixin

**Comment by Yiannis128** [comment]
Hi, can you send a picture? Also, did you read the [Initial Setup](https://github.com/Yiannis128/esbmc-ai/wiki/Initial-Setup) instructions in the wiki?
