### ISSUE TITLE
Simplify the trace?

### ISSUE THREAD

**Issue by ChenfengWei0** [esbmc/esbmc-ai#149]
Hi @Yiannis128,

I was wondering if there is any strategy in ESBMC-AI to simplify the output trace from ESBMC before sending it to the LLMs. The idea is to remove the unnecessary state step in the counterexample trace. 

For instance, a potential/general solution is to remove all the state steps that go into the header file, which can be identified by the filename, e.g.  `string.c`, `temp_sol.cpp`

**Comment by Yiannis128** [comment]
Hi @ChenfengWei0,

It does support it but on a more basic level than you specified in your examples. In the config you can set the entry `esbmc.output_type` to the following values:

* `full`: Default
* `ce`: Will output everything below and including the counterexample section
* `vp`: Will only output the violated property section

**Comment by ChenfengWei0** [comment]
I think it might be a good idea to contain both the trace and ce. Also we can beautify the output from the esbmc, which frankly speaking is not that readable. 

E.g.
```
[Counterexample]


State 1 file 1.c line 16 column 6 function main thread 0
----------------------------------------------------
  N = 4194304 (00000000 01000000 00000000 00000000)

State 2 file 1.c line 22 column 2 function main thread 0
----------------------------------------------------
  a = (signed int *)0

State 3 file 1.c line 27 column 4 function main thread 0
----------------------------------------------------
Violated property:
  file 1.c line 27 column 4 function main
  dereference failure: NULL pointer


VERIFICATION FAILED
```

to

```
Counterexample and traces:

line 16 function main: N = 4194304 

line 22 function main: a = (signed int *)0

line 27 function main: Violated property: dereference failure: NULL pointer

VERIFICATION FAILED
```

> a potential/general solution is to remove all the state steps that go into the header file, which can be identified by the filename, e.g. string.c, temp_sol.cpp

Also, this one as a filter could be beneficial. 

I prefer to implement this as an option (e.g. `--simplified-trace`) in ESBMC.

**Comment by lucasccordeiro** [comment]
I liked your suggestion, @ChenfengWei0.

**Comment by lucasccordeiro** [comment]
This PR https://github.com/esbmc/esbmc/pull/2208 is merged.
